api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "cro-bundles"
uid = "1c165547-840b-bd29-9781-c856f04c4f39f0fb6472"
type = "function"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "src/cart_transform_run.graphql"
  export = "cart-transform-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
