query CartTransformRunInput($collections: [ID!]) {
  presentmentCurrencyRate
  cart {
    lines {
      id
      quantity
      bundle: attribute(key: "_bundle") {
        value
      }
      cost {
        amountPerQuantity {
          amount
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
          }
          inCollections(ids: $collections) {
            collectionId
            isMember
          }
        }
      }
    }
  }
  cartTransform {
    metafield(namespace: "$app", key: "bundles") {
      jsonValue
    }
  }
}
