query CartInput($collectionIds: [ID!]) {
  cart {
    lines {
      id
      quantity
      bundle: attribute(key: "_bundle_components") {
        value
      }
      merchandise {
        __typename
        ... on ProductVariant {
          title
          product {
            id
            inCollections(ids: $collectionIds) {
              collectionId
              isMember
            }
          }
        }
      }
    }
  }
  discount {
    discountClasses
    metafield(namespace: "$app", key: "function-configuration") {
      jsonValue
    }
  }
}
